[package]
name = "gc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.132"
bincode = "1.3.3"
clap = { version = "4.5.32", features = ["derive"] }
serde = { version = "1.0.213", features = ["derive"] }
rand = "0.8.5"
itertools = "0.13"
memmap = "0.7.0"
