# rng config file
# space separated
# lines with # are ignored
# use 1 for true and 0 for false

# stream to fpga
rng_target  /dev/xdma0_h2c_1

# true RNG from USB stick
use_trng    1
trng_source /dev/ttyRNG0

# prng (rdseed + aes) xored with trng
use_prng    1

